services:
  web:
    build:
      args:
        PUBLIC_URL: /home
      context: ./ld-fe
    ports:
      - "3010:80"
    container_name: web-link-dashboard
    networks:
      - app-network

  back:
    build:
      context: ./ld-be
    ports:
      - "8001:8080"
    volumes:
      - ./misc:/app/misc
    container_name: back-link-dashboard
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
